/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ActivityTracker.Controller;

import ActivityTracker.model.SegmentTypes;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-07-25T01:21:42.638116-04:00[America/Toronto]")

@Validated
@Api(value = "segmentTypes", description = "the segmentTypes API")
public interface SegmentTypesApi {

    default SegmentTypesApiDelegate getDelegate() {
        return new SegmentTypesApiDelegate() {};
    }

    /**
     * GET /segmentTypes : obtains all segment types
     * gets all the segment types
     *
     * @return Returned all segment types (status code 200)
     *         or Did not work. (status code 400)
     */
    @ApiOperation(value = "obtains all segment types", nickname = "getAllSegmentTypes", notes = "gets all the segment types", response = SegmentTypes.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returned all segment types", response = SegmentTypes.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Did not work.") })
    @RequestMapping(value = "/segmentTypes",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<SegmentTypes>> getAllSegmentTypes() {
        return getDelegate().getAllSegmentTypes();
    }

}
